# src/AppBundle/Resources/config/doctrine/CrimePoiMap.orm.yml
AppBundle\Entity\CrimePoiMap:
    type: entity
    table: Crimepoimap
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        long:
            type: float
        lat:
            type: float
        date:
            type: text
        idloc:
            type: text
