# src/AppBundle/Resources/config/doctrine/CrimePoiSample.orm.yml
AppBundle\Entity\FirePoiSample:
    type: entity
    table: Firepoisample
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        long:
            type: float
        lat:
            type: float
        date:
            type: text
        idloc:
            type: text
