# src/AppBundle/Resources/config/doctrine/FirePoi.orm.yml
AppBundle\Entity\FirePoi:
    type: entity
    table: Firepoi
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        long:
            type: float
        lat:
            type: float
        date:
            type: text
        loc:
            type: text
